//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFastFood {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eFastFood.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem s internetom..
        /// </summary>
        internal static string connec_err {
            get {
                return ResourceManager.GetString("connec_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email već registrovan..
        /// </summary>
        internal static string email_exist {
            get {
                return ResourceManager.GetString("email_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresa u neispravnom formatu..
        /// </summary>
        internal static string email_format {
            get {
                return ResourceManager.GetString("email_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje ne smije biti prazno.
        /// </summary>
        internal static string empty_string {
            get {
                return ResourceManager.GetString("empty_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinke se ne podudaraju..
        /// </summary>
        internal static string password_not_match {
            get {
                return ResourceManager.GetString("password_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona već registrovan..
        /// </summary>
        internal static string phone_exist {
            get {
                return ResourceManager.GetString("phone_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste registrovani..
        /// </summary>
        internal static string registration_success {
            get {
                return ResourceManager.GetString("registration_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je manje od 50 karaktera..
        /// </summary>
        internal static string string_length50 {
            get {
                return ResourceManager.GetString("string_length50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspijeh.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnički podaci uspješno snimljeni..
        /// </summary>
        internal static string user_updated {
            get {
                return ResourceManager.GetString("user_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogrešno korisničko ime ili lozinka..
        /// </summary>
        internal static string wrong_user_or_pass {
            get {
                return ResourceManager.GetString("wrong_user_or_pass", resourceCulture);
            }
        }
    }
}
