//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFastFood_API.Models
{
    using System;

    public partial class Dostava
    {
        public int DostavaID { get; set; }
        public int NarudzbaID { get; set; }
        public Nullable<int> UposlenikID { get; set; }
        public string AdresaDostave { get; set; }
        public Nullable<System.DateTime> VrijemePreuzimanja { get; set; }
        public Nullable<System.DateTime> VrijemeDostavljanja { get; set; }

        public virtual Narudzba Narudzba { get; set; }
        public virtual Uposlenik Uposlenik { get; set; }
    }
}
