//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFastFood_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NarudzbaStavka
    {
        public int NarudzbaStavkaID { get; set; }
        public int Kolicina { get; set; }
        public Nullable<bool> UPripremi { get; set; }
        public Nullable<bool> Gotovo { get; set; }
        public Nullable<int> NarudzbaID { get; set; }
        public Nullable<int> GotoviProizvodID { get; set; }
    
        public virtual GotoviProizvod GotoviProizvod { get; set; }
        public virtual Narudzba Narudzba { get; set; }
    }
}
