//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFastFood_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocjena
    {
        public int OcjenaID { get; set; }
        public int NumerickaOcjena { get; set; }
        public string Komentar { get; set; }
        public int GotoviProizvodID { get; set; }
        public int KlijentID { get; set; }
    
        public virtual GotoviProizvod GotoviProizvod { get; set; }
        public virtual Klijent Klijent { get; set; }
    }
}
