//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFastFood_API.Models
{
    using System;

    public partial class Racun
    {
        public int RacunID { get; set; }
        public string BrojRacuna { get; set; }
        public System.DateTime DatumIzdavanja { get; set; }
        public Nullable<decimal> CijenaBezPDV { get; set; }
        public Nullable<decimal> CijenaSaPDV { get; set; }
        public string VrstaPlacanja { get; set; }
        public Nullable<bool> IsPlaceno { get; set; }
        public Nullable<int> UposlenikID { get; set; }
        public Nullable<int> NarudzbaID { get; set; }

        public virtual Narudzba Narudzba { get; set; }
        public virtual Uposlenik Uposlenik { get; set; }
    }
}
